# Setup
title:            CoMPAS Architecture
tagline:          'Architecture of the CoMPAS project'

paginate:       5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/com-pas/compas-architecture

github_username:  Flurb
git_repo:         compas-architecture
git_branch:       PAGES

baseurl:          /{{ git_repo }}/