# Setup
title:            CoMPAS Architecture
tagline:          'Architecture of the CoMPAS project'
baseurl:          /

gems:           [jekyll-paginate]
paginate:       5
paginate_path:  "page:num"

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/com-pas/compas-architecture
