# Setup
title:            CoMPAS Architecture
tagline:          'Architecture of the CoMPAS project'

paginate:         5

# Custom vars
version:          0.0.2

github:
  repo:           https://github.com/com-pas/compas-architecture

github_username:  com-pas
git_repo:         compas-architecture
git_branch:       Issue_18

baseurl:          /compas-architecture

plugins:
  - jekyll-readme-index