# Permalinks
permalink:        pretty

# Setup
title:            CoMPAS Architecture
tagline:          'Architecture of the CoMPAS project'
baseurl:          /

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/com-pas/compas-architecture
